replicaCount: 5

image:
  repository: "bskeshab76820/creactapp"
  pullPolicy: Always
  tag: "v1"

imagePullSecrets: []
nameOverride: "creactapp"
fullnameOverride: "creactapp-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "react"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort #ClusterIP
  port: 80

resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
